"""add unit cost to stock

Revision ID: 12c084c78bb6
Revises: f91cfa64699f
Create Date: 2026-07-21 19:25:53.618750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c084c78bb6'
down_revision: Union[str, Sequence[str], None] = 'f91cfa64699f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'unit_cost')
    # ### end Alembic commands ###
