"""link employee with designation

Revision ID: e0f017462ff9
Revises: 567a2bc3543f
Create Date: 2026-07-19 12:50:35.304009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f017462ff9'
down_revision: Union[str, Sequence[str], None] = '567a2bc3543f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('designation_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'employees', 'designations', ['designation_id'], ['id'])
    op.drop_column('employees', 'designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'designation_id')
    # ### end Alembic commands ###
