"""add customer payment 

Revision ID: e95f097ad310
Revises: 3915cfd192c0
Create Date: 2026-07-20 21:00:03.067470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95f097ad310'
down_revision: Union[str, Sequence[str], None] = '3915cfd192c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_payments',
    sa.Column('payment_number', sa.String(length=30), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('sales_invoice_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK', 'UPI', 'CHEQUE', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='customerpaymentstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_payments_payment_number'), 'customer_payments', ['payment_number'], unique=True)
    op.add_column('sales_invoices', sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('sales_invoices', sa.Column('balance_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_invoices', 'balance_amount')
    op.drop_column('sales_invoices', 'paid_amount')
    op.drop_index(op.f('ix_customer_payments_payment_number'), table_name='customer_payments')
    op.drop_table('customer_payments')
    # ### end Alembic commands ###
