"""add product category table

Revision ID: eef8c448abc4
Revises: 92ab320980db
Create Date: 2026-07-19 14:56:17.618654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef8c448abc4'
down_revision: Union[str, Sequence[str], None] = '92ab320980db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_category_code'), 'product_categories', ['category_code'], unique=True)
    op.create_index(op.f('ix_product_categories_category_name'), 'product_categories', ['category_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_categories_category_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_category_code'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
