"""add cash flow category to chart of accounts

Revision ID: f91cfa64699f
Revises: 621c98b0994e
Create Date: 2026-07-21 19:03:25.196838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91cfa64699f'
down_revision: Union[str, Sequence[str], None] = '621c98b0994e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
     cashflow_enum = sa.Enum(
        "OPERATING",
        "INVESTING",
        "FINANCING",
        name="cashflowcategory",
    )

    # Create the PostgreSQL enum type first
     cashflow_enum.create(op.get_bind(), checkfirst=True)

    # Then add the column
     op.add_column(
        "chart_of_accounts",
        sa.Column(
            "cash_flow_category",
            cashflow_enum,
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_of_accounts', 'cash_flow_category')
    # ### end Alembic commands ###
